version: '3.0'

services:
  token: 
    container_name: vany-sms-api
    image: vany-sms-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 7005:7005
    networks:
      - SMSServiceNet 

networks: 
  SMSServiceNet: